export const SET_ORDER_DETAILS_LOADING = 'SET_ORDER_DETAILS_LOADING'
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const SET_ORDER_DETAILS_ERROR = 'SET_ORDER_DETAILS_ERROR'
export const CLEAR_ORDER_DETAILS_ERROR = 'CLEAR_ORDER_DETAILS_ERROR'
